# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

 pod 'Firebase/Storage'
pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Analytics'

target 'SampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SampleApp

end
